#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#    - username
#    - user id
#    - Home directory path for the user
#Requirements:

file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _
do
    echo "$username:$uid:$home"
done < "$file"
