#!/usr/bin/env bash
#Write a Bash script that displays:
#    - The content of the current directory
#    - In a list format
#    - Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
    if [ -f "$file" ] && [ ! -d "$file" ] && [[ "$file" != .* ]]
    then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi

done
